vkd3d: BLOB PIX markers decoding
HansKristian-Work/vkd3d-proton pull request #1202
Opened 2022-08-30 01:27 UTC by Dragon31337

PIX Events Markers ( https://devblogs.microsoft.com/pix/winpixeventruntime/ ), which is the most used and the only recommended way to insert Perf Markers, see ( https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12commandqueue-beginevent )
PIXEventType enum values, masks, offsets, and encoding can be extracted from the source code in the original package
https://www.nuget.org/packages/WinPixEventRuntime
at \Include\WinPixEventRuntime\, mostly in PIXEventsCommon.h

2022-08-30 08:53 UTC, HansKristian-Work commented
We are in a process of relicensing to MIT. Before we can accept this PR, do you consent to your contribution being relicensed to MIT?

2022-08-30 17:11 UTC, Dragon31337 commented
Yes, I do consent to my contribution being relicensed to MIT.

2022-08-31 09:04 UTC, HansKristian-Work requested changes
The formatting here is all over the place.

- Inverse christmas tree for variables.
- Put all variables on top (C89 style).
- 4 space indents.
- Snake case.
- Pointer asterisk ties right.

Also, missing Signed-off-by line (`git commit --amend -s`)

2022-08-31 13:30 UTC, Joshua-Ashton requested changes

2022-08-31 13:30 UTC, Joshua-Ashton commented on libs/vkd3d/command.c
> +    StrLength = strnlen_s((const char*)data64, SIZE_MAX);
Just use `strlen`. It's not useful to use `strnlen` here to protect against iterating over the whole address space. :frog:


FTR: The `_s` functions are originally meme MSVC extensions that got erroneously promoted in C11, when they should have just used the ubiquitous POSIX standard ones. If you do need to use `strnlen` again, just use `strnlen`.

2022-08-31 21:47 UTC, Dragon31337 commented
I'm not sure if I should keep PIX consts and enum names or convert those too. I would keep it for reference to the original code in PIXEventsCommon.h

2022-09-01 13:31 UTC, HansKristian-Work requested changes

2022-09-01 13:31 UTC, HansKristian-Work commented on libs/vkd3d/command.c
> +    UINT64* data_uint64_aligned = (UINT64*)(data);
`const UINT64 *data_uint64_aligned = data;`

2022-09-01 13:31 UTC, HansKristian-Work commented on libs/vkd3d/command.c
> +static char* decode_pix_blob(const void* data, size_t size)
`static char *` and `const void *data`

2022-09-01 13:31 UTC, HansKristian-Work commented on libs/vkd3d/command.c
> +        ePIXEvent_EndEvent = 0x000,
I guess it's fine to keep the enums like this.

2022-09-01 13:31 UTC, HansKristian-Work commented on libs/vkd3d/command.c
> +    data_uint64_aligned++; //skip Color
Use C89 style comments `/* */`

2022-09-01 13:31 UTC, HansKristian-Work commented on libs/vkd3d/command.c
> +        memcpy(label_str, (const char*)data_uint64_aligned, label_str_length);
No need to cast `data_uint64_aligned` here.

2022-09-01 13:31 UTC, HansKristian-Work commented on libs/vkd3d/command.c
> +        label_str_length = wcslen((const wchar_t*)data_uint64_aligned);
Don't bother checking length here.

2022-09-01 13:31 UTC, HansKristian-Work commented on libs/vkd3d/command.c
> +        label_str = vkd3d_strdup_w_utf8((const wchar_t*)data_uint64_aligned, label_str_length);
Deduce the length based on `size`, subtracted by the blob offset. Also it's `WCHAR` not `wchar_t`. The C type is 32-bit on Linux, but we explicitly need 16-bit.

2022-09-01 13:33 UTC, DadSchoorse commented on libs/vkd3d/command.c
> +        label_str_length = wcslen((const wchar_t*)data_uint64_aligned);
Use `vkd3d_wcslen((const WCHAR*) ...)` WCHAR is always utf16. wchar_t is platform dependent.

2022-09-01 13:34 UTC, DadSchoorse commented on libs/vkd3d/command.c
> +        label_str_length = wcslen((const wchar_t*)data_uint64_aligned);
actually, you can drop this completely. vkd3d_strdup_w_utf8 will stop at a null terminator.

2022-09-01 13:35 UTC, DadSchoorse commented on libs/vkd3d/command.c
> +        label_str = vkd3d_strdup_w_utf8((const wchar_t*)data_uint64_aligned, label_str_length);
`vkd3d_strdup_w_utf8((const WCHAR *)data_uint64_aligned, 0)`

2022-09-01 13:37 UTC, DadSchoorse commented on libs/vkd3d/command.c
> +        label_str[label_str_length] = '\0';
Just use `vkd3d_strdup`.

2022-09-01 14:04 UTC, DadSchoorse commented on libs/vkd3d/command.c
> +        label_str_length = wcslen((const wchar_t*)data_uint64_aligned);
actually I ignore me and use the blob length like themaister said

2022-09-03 16:51 UTC, Dragon31337 commented
THanks for your help and feedback. Are there any items left?

2022-09-05 14:15 UTC, HansKristian-Work approved these changes
LGTM

2022-09-05 14:15 UTC, merged