vkd3d: Add VKD3D_SHADER_MODEL override.
HansKristian-Work/vkd3d-proton pull request #1495
Opened 2023-03-28 20:43 UTC by CME42

This makes it possible to run tlou1 on pascal, but may cause unexpected results.

2023-03-28 23:13 UTC, CME42 commented on libs/vkd3d/device.c
> +        { "6.6", D3D_SHADER_MODEL_6_6 },
seems like D3D_SHADER_MODEL_6_7 is not in the enum yet, shall i just add it?

2023-03-29 09:30 UTC, CME42 commented
> Can we make this 6_1 to match the feature level formatting?

I thought VKD3D_SHADER_MODEL=6_6 looks ugly so I made dots out of it 🐸 But I don't really mind, can change that to underscore.

2023-03-29 13:54 UTC, HansKristian-Work requested changes

2023-03-29 13:54 UTC, HansKristian-Work commented on libs/vkd3d/device.c
> +static void d3d12_device_caps_shader_model_override(struct d3d12_device *device) {
Brace placement

2023-03-29 13:54 UTC, HansKristian-Work commented on libs/vkd3d/device.c
> +        const char* string;
`const char *string`

2023-03-29 13:54 UTC, HansKristian-Work commented on libs/vkd3d/device.c
> +        { "6.6", D3D_SHADER_MODEL_6_6 },
Add it to IDL, yes.

2023-03-29 13:54 UTC, HansKristian-Work commented on libs/vkd3d/device.c
> +    } else {
```
if ()
{
}
else
{
}
```

2023-03-29 13:55 UTC, HansKristian-Work commented
> Can we make this 6_1 to match the feature level formatting?

It also matches how you invoke DXC. `-Tcs_6_4` for example.

2023-03-29 16:41 UTC, HansKristian-Work requested changes
Smol nit, then lgtm. Before taking this, do you consent to this being relicensed to MIT as well?

2023-03-30 10:33 UTC, HansKristian-Work approved these changes
LGTM

2023-03-30 10:41 UTC, merged