vkd3d: Implement D3D12_HEAP_TYPE_WRITE_WATCH
HansKristian-Work/vkd3d-proton pull request #587
Opened 2021-03-17 21:59 UTC by Joshua-Ashton

Needed for D3D12 APITrace

Closes: #373
Signed-off-by: Joshua Ashton <joshua@froggi.es>

2021-03-17 23:25 UTC, Joshua-Ashton commented
Works under Windows, doesn't under wine because the `WRITE_WATCH` pointer fails to import.

I imagine there is some difference here in the way that Wine is emulating `WRITE_WATCH` that breaks somewhere down the line.

2021-03-17 23:30 UTC, Joshua-Ashton commented
To test you can use `APITRACE_FORCE_MODULE_PATH=C:\Users\Joshua\Desktop\vkd3d-proton-write-watch\x64`, etc to point to your VKD3D-Proton + DXVK DXGI dlls for APITrace to use.

2021-03-18 10:03 UTC, HansKristian-Work commented on libs/vkd3d/memory.c
> +    void *host_ptr = info->host_ptr;
:christmas_tree:

2021-03-18 10:05 UTC, HansKristian-Work commented on libs/vkd3d/memory.c
> +static void *vkd3d_allocate_write_watch_pointer(const D3D12_HEAP_PROPERTIES* properties, VkDeviceSize size)
`*` binds to right

2021-03-18 10:06 UTC, HansKristian-Work requested changes
Nit, otherwise LGTM.

2021-03-18 13:41 UTC, HansKristian-Work approved these changes
LGTM

2021-03-18 13:41 UTC, merged