Fixing CopyTextureRegion going out of bounds when src_box is null.
HansKristian-Work/vkd3d-proton pull request #756
Opened 2021-07-27 20:25 UTC by dave-juicelabs

2021-07-27 20:27 UTC, dave-juicelabs commented
This issue came about by having a src image with size (1840, 1840, 1) and a destination image with size (1024, 1024, 1). src_box was null and the src image size was causing an error during vkCmdCopyImage.

2021-07-27 21:16 UTC, Joshua-Ashton requested changes
Please add a test case for this also.

2021-07-27 21:16 UTC, Joshua-Ashton commented on libs/vkd3d/command.c
> +        miplevel = image_copy->dstSubresource.mipLevel;
Just pass this directly to vk_extent_3d_from_d3d12_miplevel... Same for the above srcSubresource.

2021-07-27 21:16 UTC, Joshua-Ashton commented on libs/vkd3d/command.c
> +        if((dst_x + image_copy->extent.width) > dstExtent.width)
Use min here.

2021-07-28 16:23 UTC, Joshua-Ashton requested changes
Please split the test change into another commit before the original one.

2021-07-29 15:28 UTC, HansKristian-Work approved these changes
LGTM

2021-07-29 15:28 UTC, merged