Add a generic set of UE4 quirks
HansKristian-Work/vkd3d-proton pull request #826
Opened 2021-10-03 02:11 UTC by Joshua-Ashton

I encountered another game, Bus Simulator 22, which has the same broken shader as Necromunda, including the same hash.

Looks like a bunch of UE4 games are affected, so check if the exe name ends in `-Shipping.exe` and apply these quirks for these shader hashes going forward.

I reeeeally would have liked to have done a regex here, but it looks like there's nothing nice and portable in the std and pulling in some external dependency is kinda gross, there is this which was licensed nice and is small however https://github.com/kokke/tiny-regex-c if we want to consider it.

Fixes Bus Simulator 22

2021-10-04 11:59 UTC, HansKristian-Work requested changes

2021-10-04 11:59 UTC, HansKristian-Work commented on include/private/vkd3d_string.h
> +    return str_len >= ending_len && !strcmp(str + (str_len - ending_len), ending);
_n naming here is somewhat misleading, since I would expect that to only look at len number of characters (i.e. strncmp).

2021-10-04 11:59 UTC, HansKristian-Work commented on libs/vkd3d/device.c
> +/* Checks if the end of the application's name matches. */
I would instead add a compare mode field to the vkd3d_shader_quirk_meta, where we either go for exact or "ends with" matching. Would also allows us to add "begins with" and "contains" later if necessary.

2021-10-07 08:58 UTC, HansKristian-Work requested changes
Trivial nit

2021-10-07 08:58 UTC, HansKristian-Work commented on include/private/vkd3d_string.h
> +    };
weird semicolon

2021-10-07 09:07 UTC, Joshua-Ashton commented on include/private/vkd3d_string.h
> +    };
Dunno how he got there, fixed.

2021-10-07 09:18 UTC, merged